"""Local SQLite store for the audit log, connector consents and escalation tickets.

Designed around the Digital Personal Data Protection Act's principles:
- Data minimisation: audit events record a hash and the length of a question, not its
  text, unless AUDIT_STORE_QUERY_TEXT is enabled. Escalations keep the question only
  because the user explicitly submits it to a human.
- Sessions are anonymous random ids generated by the browser; no account or name.
- Right of access and erasure: everything is retrievable and deletable per session.
- Retention: rows older than AUDIT_RETENTION_DAYS are purged at startup.

All methods are synchronous and fast (single-row writes); call them from async code via
`run_in_threadpool`.
"""

import hashlib
import json
import secrets
import sqlite3
import threading
from datetime import UTC, datetime, timedelta
from pathlib import Path

_SCHEMA = """
CREATE TABLE IF NOT EXISTS audit_events (
    id INTEGER PRIMARY KEY,
    ts TEXT NOT NULL,
    session_id TEXT NOT NULL,
    event TEXT NOT NULL,
    detail TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS audit_session ON audit_events(session_id);
CREATE TABLE IF NOT EXISTS consents (
    id INTEGER PRIMARY KEY,
    ts TEXT NOT NULL,
    session_id TEXT NOT NULL,
    connector TEXT NOT NULL,
    granted INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS consent_session ON consents(session_id);
CREATE TABLE IF NOT EXISTS escalations (
    id TEXT PRIMARY KEY,
    ts TEXT NOT NULL,
    session_id TEXT NOT NULL,
    question TEXT NOT NULL,
    jurisdiction TEXT NOT NULL,
    contact TEXT,
    status TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS escalation_session ON escalations(session_id);
"""


def _now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


class Store:
    def __init__(self, path: Path | str, store_query_text: bool = False):
        if str(path) != ":memory:":
            Path(path).parent.mkdir(parents=True, exist_ok=True)
        self._db = sqlite3.connect(str(path), check_same_thread=False)
        self._db.row_factory = sqlite3.Row
        self._lock = threading.Lock()
        self._store_query_text = store_query_text
        with self._lock, self._db:
            self._db.execute("PRAGMA journal_mode=WAL")
            self._db.executescript(_SCHEMA)

    def close(self) -> None:
        self._db.close()

    # ---- audit ----

    def log_question(self, session_id: str, query: str, **detail) -> None:
        """Record that a question was answered, without storing its text by default."""
        detail = {
            "query_sha256": hashlib.sha256(query.encode("utf-8")).hexdigest(),
            "query_chars": len(query),
            **detail,
        }
        if self._store_query_text:
            detail["query"] = query
        self.log_event(session_id, "question", detail)

    def log_event(self, session_id: str, event: str, detail: dict) -> None:
        with self._lock, self._db:
            self._db.execute(
                "INSERT INTO audit_events (ts, session_id, event, detail) VALUES (?, ?, ?, ?)",
                (_now(), session_id, event, json.dumps(detail, ensure_ascii=False)),
            )

    # ---- consents for paid sources ----

    def set_consent(self, session_id: str, connector: str, granted: bool) -> dict:
        ts = _now()
        with self._lock, self._db:
            self._db.execute(
                "INSERT INTO consents (ts, session_id, connector, granted) VALUES (?, ?, ?, ?)",
                (ts, session_id, connector, int(granted)),
            )
        return {"connector": connector, "granted": granted, "logged_at": ts}

    def consents(self, session_id: str) -> dict[str, bool]:
        """Latest consent decision per connector for this session."""
        with self._lock:
            rows = self._db.execute(
                "SELECT connector, granted FROM consents WHERE session_id = ? ORDER BY id",
                (session_id,),
            ).fetchall()
        return {r["connector"]: bool(r["granted"]) for r in rows}

    # ---- escalations ----

    def create_escalation(
        self, session_id: str, question: str, jurisdiction: str, contact: str | None
    ) -> dict:
        ticket = {
            "id": "ESC-" + secrets.token_hex(3).upper(),
            "ts": _now(),
            "session_id": session_id,
            "question": question,
            "jurisdiction": jurisdiction,
            "contact": contact,
            "status": "open",
        }
        with self._lock, self._db:
            self._db.execute(
                "INSERT INTO escalations (id, ts, session_id, question, jurisdiction, contact, status) "
                "VALUES (:id, :ts, :session_id, :question, :jurisdiction, :contact, :status)",
                ticket,
            )
        return ticket

    # ---- data-principal rights ----

    def activity(self, session_id: str, limit: int = 100) -> list[dict]:
        """Everything stored for a session, newest first."""
        with self._lock:
            audit = self._db.execute(
                "SELECT ts, event, detail FROM audit_events WHERE session_id = ? ORDER BY id DESC LIMIT ?",
                (session_id, limit),
            ).fetchall()
            consents = self._db.execute(
                "SELECT ts, connector, granted FROM consents WHERE session_id = ? ORDER BY id DESC LIMIT ?",
                (session_id, limit),
            ).fetchall()
            escalations = self._db.execute(
                "SELECT id, ts, question, jurisdiction, contact, status FROM escalations "
                "WHERE session_id = ? ORDER BY ts DESC LIMIT ?",
                (session_id, limit),
            ).fetchall()
        items = [{"ts": r["ts"], "type": r["event"], "detail": json.loads(r["detail"])} for r in audit]
        items += [
            {
                "ts": r["ts"],
                "type": "consent",
                "detail": {"connector": r["connector"], "granted": bool(r["granted"])},
            }
            for r in consents
        ]
        items += [
            {"ts": r["ts"], "type": "escalation", "detail": {k: r[k] for k in r.keys() if k != "ts"}}
            for r in escalations
        ]
        items.sort(key=lambda i: i["ts"], reverse=True)
        return items[:limit]

    def erase(self, session_id: str) -> int:
        """Delete every row for a session. Returns the number of rows removed."""
        removed = 0
        with self._lock, self._db:
            for table in ("audit_events", "consents", "escalations"):
                removed += self._db.execute(
                    f"DELETE FROM {table} WHERE session_id = ?", (session_id,)
                ).rowcount
        return removed

    def purge_older_than(self, days: int) -> int:
        cutoff = (datetime.now(UTC) - timedelta(days=days)).isoformat(timespec="seconds")
        removed = 0
        with self._lock, self._db:
            for table in ("audit_events", "consents", "escalations"):
                removed += self._db.execute(f"DELETE FROM {table} WHERE ts < ?", (cutoff,)).rowcount
        return removed
